- src/main/java/org/jenkinsci/plugins/docker/commons/DockerRegistryEndpoint.java
- src/main/java/org/jenkinsci/plugins/docker/commons/DockerServerEndpoint.java
Methods are required to use EndPoints as a key in hash maps
@stephenc @reviewbybees
> Add equals() and hashcode() methods to endpoint classes

- src/main/java/org/jenkinsci/plugins/docker/commons/impl/NullKeyMaterialFactory.java
If two calls are made to contextualize from two different places with empty credentials, ie. DockerServerEndpoint and DockerRegistryEndpoint, they both reuse the same object and the second call gets IllegalStateException
@reviewbybees
> Prevent IllegalStateException when reusing the NullKeyMaterialFactory

- src/main/java/org/jenkinsci/plugins/docker/commons/fingerprint/DockerAncestorFingerprintFacet.java
https://github.com/jglick/docker-commons-plugin/commit/91fdceac63148f267141bf681a2b8726770df6d0 in #21 led to the situation that the ancestor ID set is actually empty.
It would have been nice if Docker assigned the ID `0000000000000000000000000000000000000000000000000000000000000000` (or anything, really) to the empty image. But it does not seem to have a concept of zero:
```
$ docker inspect -f {{.Parent}} ubuntu
$ docker inspect scratch
Error: No such image or container: scratch
[]
```
The choices here are:
* Use `null` as the parameter to `addFromFacet`, as I have done, but do not add it to `DockerAncestorFingerprintFacet.ancestorImageIds`.
* Do not even create the `DockerAncestorFingerprintFacet` (but if it already exists, leave its `ancestorImageIds` unmodified).
* Add a `null` to …
> Javadoc refinement relating to base images

- src/main/java/org/jenkinsci/plugins/docker/commons/fingerprint/DockerFingerprints.java
This public method is useful, because it allows to avoid a high-cost Fingerprint loading during hash calculations (e.g. links in web interfaces).
@reviewbybees
> Introduce DockerFingerprints::getImageFingerprintHash() method.

- src/main/resources/org/jenkinsci/plugins/docker/commons/lib/selectDockerTool.jelly
For users (most of them imho) who will just rely on docker installation in default PATH
> hide Docker installation option if no installation is defined

- src/main/java/org/jenkinsci/plugins/docker/commons/credentials/DockerServerCredentials.java
- src/main/resources/org/jenkinsci/plugins/docker/commons/credentials/DockerServerEndpoint/config.jelly
- src/main/resources/org/jenkinsci/plugins/docker/commons/credentials/DockerServerEndpoint/help-uri.html
as this is what is used by Docker as well as env variable used by docker user to point to a docker daemon 
and we called « DockerServerEndpoint » in our own vocable
> prefer « Docker Host » terminology

- src/main/java/org/jenkinsci/plugins/docker/commons/credentials/DockerRegistryToken.java
Hi,
I found a bug in the source code, when you install the plugin and docker 1.7.0 for the first time, it will create a config.json file which is fine for the new version but the Json format will use the old version which doesn't work with the 1.7.0
So by default for backward compatibilty, I create the old version in the old file and docker event the new version will be able to use it.
> [FIXED-JENKINS-29627] - Fix issue with new docker version

- src/main/java/org/jenkinsci/plugins/docker/commons/credentials/DockerRegistryToken.java
- src/main/java/org/jenkinsci/plugins/docker/commons/credentials/KeyMaterial.java
- src/main/java/org/jenkinsci/plugins/docker/commons/credentials/KeyMaterialFactory.java
- src/main/java/org/jenkinsci/plugins/docker/commons/impl/ServerKeyMaterialFactory.java
- src/test/java/org/jenkinsci/plugins/docker/commons/fingerprint/DockerRunFingerprintFacetTest.java
This pull request is focused on resolving occurrences of Sonar rule "squid:S1213 -  The members of an interface declaration or class should appear in a pre-defined order". You can find more information about the issue here: https://dev.eclipse.org/sonar/rules/show/squid:S1213
Please let me know if you have any questions.
Sameer Misger
> Fixing squid:S1213 - The members of an interface declaration or class should appear in a pre-defined order

- pom.xml
- src/main/java/org/jenkinsci/plugins/docker/commons/credentials/DockerRegistryEndpoint.java
- src/main/java/org/jenkinsci/plugins/docker/commons/credentials/DockerRegistryToken.java
> [JENKINS-38018] Extend DockerRegistryEndpoint API to take a Launcher and TaskListener

- src/main/java/org/jenkinsci/plugins/docker/commons/credentials/DockerRegistryEndpoint.java
- src/test/java/org/jenkinsci/plugins/docker/commons/credentials/DockerRegistryEndpointTest.java
This issue was discovered in the docker-workflow-plugin. 
Given the following pipeline code:
`docker.withRegistry('http://localhost:5000/') {`
`def dockerImage = docker.image('localhost:5000/test-image')`
`dockerImage.inside {`
`echo "container running on ${port}"`
`}`
`}`
The rendered "docker pull" command incorrectly builds the qualified image name as: 
_localhost:5000/localhost:5000/test-image_
This PR adds a condition to check whether or not the image name already contains the registry prefix to avoid appending again.
cc: @genehand
> [JENKINS-39181] Invalid fully qualified image name when registry URL specified

- pom.xml
- src/test/java/org/jenkinsci/plugins/docker/commons/credentials/DockerServerCredentialsTest.java
- src/test/java/org/jenkinsci/plugins/docker/commons/credentials/DockerServerDomainSpecificationTest.java
With the new changes to the plugin compatibility tester, a few of this plugin's tests fail, specifically `DockerServerCredentialsTest` and `DockerServerDomainSpecificationTest`. Currently, it depends on the 1.x line of the credentials plugin. Since there were significant changes with this plugin upon the 2.x release & the plugin compat tester tests compatibility against the most recent or bundled version of the plugin, the tests are failing even though there are really no issues. I have run all the docker-commons tests using `mvn test` as well as through the plugin compat tester, and there are now no errors.
Removed the check of a url that is incompatable across a major release.  This type of check can be done in the acceptance test harness.
@reviewbybees
> Fix PCT Test Failures

- Jenkinsfile
- pom.xml
- src/test/java/org/jenkinsci/plugins/docker/commons/tools/DockerToolInstallerTest.java
Not sure why it was here—was actually older than what you would get by default anyway. Cf. https://github.com/jenkinsci/plugin-pom/pull/72.
@reviewbybees
> Remove icon-shim dependency

- src/main/java/org/jenkinsci/plugins/docker/commons/impl/ServerKeyMaterialFactory.java
- src/test/java/org/jenkinsci/plugins/docker/commons/credentials/DockerServerEndpointTest.java
See [JENKINS-36088](https://issues.jenkins-ci.org/browse/JENKINS-36088?focusedCommentId=322239&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-322239) and subsequent comments. Before Jenkins 2.93, calling `FilePath#chmod` on a non-existent file or directory would fail silently, now it will throw `NoSuchFileException`. There appears to be an incorrect usage here that went unnoticed because the calls to`ServerKeyMaterialFactory#copyInto` call `Files#write` which creates parent directories if they do not exist.
I'm not sure why `DockerServerCredentialsBindingTest#basics` passes without this change. It runs [basics-step1.sh](https://github.com/jenkinsci/docker-commons-plugin/blob/master/src/test/resources/org/jenkinsci/plugins/docker/commons/credentials/DockerSe …
> Create directory before calling chmod

- src/main/java/org/jenkinsci/plugins/docker/commons/tools/DockerToolInstaller.java
- src/test/java/org/jenkinsci/plugins/docker/commons/tools/DockerToolInstallerTest.java
Update the plugin to use the new host and url scheme while preserving access to older images (pre 17.05.0-ce).
https://issues.jenkins-ci.org/browse/JENKINS-48674
> JENKINS-48674: downloads image for newer version from download.docker.com

- src/test/resources/org/jenkinsci/plugins/docker/commons/credentials/DockerServerCredentialsBindingTest/basics-step1.sh
it also has different format string.
> JENKINS-48783: the macOs version of stat uses the '-f', not the '-c', argument to specify the format

- src/main/java/org/jenkinsci/plugins/docker/commons/credentials/DockerRegistryEndpoint.java
- src/main/java/org/jenkinsci/plugins/docker/commons/credentials/DockerRegistryToken.java
- src/main/java/org/jenkinsci/plugins/docker/commons/credentials/DockerServerEndpoint.java
- src/main/java/org/jenkinsci/plugins/docker/commons/credentials/KeyMaterialFactory.java
- src/main/java/org/jenkinsci/plugins/docker/commons/impl/NullKeyMaterialFactory.java
- src/main/java/org/jenkinsci/plugins/docker/commons/impl/RegistryKeyMaterialFactory.java
- src/main/java/org/jenkinsci/plugins/docker/commons/impl/ServerHostKeyMaterialFactory.java
- src/main/java/org/jenkinsci/plugins/docker/commons/impl/ServerKeyMaterialFactory.java
- src/test/java/org/jenkinsci/plugins/docker/commons/util/SampleDockerBuilder.java
[JENKINS-38018](https://issues.jenkins-ci.org/browse/JENKINS-38018) and [JENKINS-28702](https://issues.jenkins-ci.org/browse/JENKINS-28702)
Supersedes #59 & #60.
@reviewbybees
> [JENKINS-38018] Use docker-login wherever possible for registry credentials

- src/main/java/org/jenkinsci/plugins/docker/commons/fingerprint/DockerFingerprintAction.java
- src/main/java/org/jenkinsci/plugins/docker/commons/fingerprint/DockerFingerprints.java
I am not sure this makes any sense. I am just trying to solve this
issue: https://issues.jenkins-ci.org/browse/JENKINS-41880
My thoughts:
This is likely caused by changing the finger prints, the finger prints
are scoped to the project (right?). If this is the case synchronising on
the project could make sense. Also `addFromFacet` should not be a
performance killer and rather quick.
The alternative would be for me to synchronise the complete access to the method.
WDYT?
> [JENKINS-41880] Synchronise on Fingerprint

- src/main/java/org/jenkinsci/plugins/docker/commons/credentials/DockerRegistryEndpoint.java
- src/main/java/org/jenkinsci/plugins/docker/commons/credentials/DockerServerEndpoint.java
- src/test/java/org/jenkinsci/plugins/docker/commons/credentials/DockerRegistryEndpointTest.java
See [JENKINS-48437](https://issues.jenkins-ci.org/browse/JENKINS-48437). This subsumes #68 from @Dohbedoh with some tweaks based on [my review comments there](https://github.com/jenkinsci/docker-commons-plugin/pull/68#pullrequestreview-220710089).
Effective diff from #68 is: https://github.com/Dohbedoh/docker-commons-plugin/compare/JENKINS-48437...dwnusbaum:JENKINS-48437.
> [JENKINS-48437] Add new APIs to retrieve Docker credentials for a Run

- src/main/java/org/jenkinsci/plugins/docker/commons/credentials/DockerRegistryEndpoint.java
- src/main/java/org/jenkinsci/plugins/docker/commons/credentials/DockerServerEndpoint.java
- src/test/java/org/jenkinsci/plugins/docker/commons/credentials/DockerRegistryEndpointTest.java
[JENKINS-48437](https://issues.jenkins-ci.org/browse/JENKINS-48437)
Proposed a fix for the issue with the method that retrieves the credentials to get the DockerRegistryToken.
Add implementation accepting a `Run` as context (and using [CredentialsProvider.findCredentialById](https://github.com/jenkinsci/credentials-plugin/blob/master/src/main/java/com/cloudbees/plugins/credentials/CredentialsProvider.java#L855-L871)) that can be later leverage by docker-workflow.
@reviewbybees
> [JENKINS-48437] Authorization for Docker Endpoint

- .mvn/extensions.xml
- pom.xml
- src/main/java/org/jenkinsci/plugins/docker/commons/credentials/DockerServerCredentials.java
- src/main/java/org/jenkinsci/plugins/docker/commons/credentials/DockerServerCredentialsBinding.java
- src/main/java/org/jenkinsci/plugins/docker/commons/impl/ServerKeyMaterialFactory.java
- src/main/java/org/jenkinsci/plugins/docker/commons/impl/ServerKeyMaterialFactoryFromDockerCredentials.java
- src/main/resources/org/jenkinsci/plugins/docker/commons/credentials/DockerServerCredentials/credentials.jelly
- src/test/java/org/jenkinsci/plugins/docker/commons/ConfigTest.java
- src/test/java/org/jenkinsci/plugins/docker/commons/credentials/DockerServerCredentialsBindingTest.java
- src/test/java/org/jenkinsci/plugins/docker/commons/credentials/DockerServerCredentialsTest.java
- src/test/java/org/jenkinsci/plugins/docker/commons/credentials/DockerServerEndpointTest.java
This updates the form UI for client keys to use the newly introduced
f:secretTextarea Jelly tag from Jenkins 2.171. Now the client key can
be more securely entered and updated.
Recreated based on #75.
@jglick @jeffret-b @Wadeck @dwnusbaum
> [JENKINS-57420] - Use f:secretTextarea for client private key

- src/main/java/org/jenkinsci/plugins/docker/commons/impl/RegistryKeyMaterialFactory.java
- src/test/java/org/jenkinsci/plugins/docker/commons/impl/RegistryKeyMaterialFactoryTest.java
When creating a new config folder, try to copy some of the properties of the existing config.json file.
Fixes [JENKINS-52724](https://issues.jenkins-ci.org/browse/JENKINS-52724) and [JENKINS-52737](https://issues.jenkins-ci.org/browse/JENKINS-52737).
> [JENKINS-52724/JENKINS-52737] Inherit properties from the local docker config.json

- src/main/java/org/jenkinsci/plugins/docker/commons/credentials/DockerServerCredentials.java
Despite initially introduced to provide authentication to a Docker host, this
credentials format is actually independant from Docker itself, and can be used
to authenticate to a TLS server using a X.509 client certificate.
So this adjusts the label accordingly so that users can discover it in an
easier way for other use cases than Docker (such as Kubernetes). See downstream usage in https://github.com/jenkinsci/kubernetes-plugin/pull/520
> Make the credentials label more generic

- src/main/java/org/jenkinsci/plugins/docker/commons/fingerprint/DockerFingerprints.java
This will prevent rare ConcurrentModificationExceptions when multiple
calls to image.inside() step is done.
This is more a carbon copy of PR-69, but for one of the neighbor methods with the same concurrency problem.
Note that I've not indented the synchronization block in order to not mess with the git history (same as in the other PR).
> [JENKINS-59501] - Add synchronization to `addRunFacet()` to prevent `ConcurrentModificationException`

- src/main/java/org/jenkinsci/plugins/docker/commons/credentials/DockerServerCredentialsHandler.java
See https://github.com/jenkinsci/pipeline-model-definition-plugin/pull/418: unused as of `pipeline-model-definition` 1.1.4 (older than the dep here).
> Deleting `CredentialsBindingHandler.toBindings`

- src/main/java/org/jenkinsci/plugins/docker/commons/impl/RegistryKeyMaterialFactory.java
This patch causes the `docker login` process to read the password from stdin rather than as an argument. Using an argument for the password causes issues with complex passwords (such as the JSON documents needed GCR) or passwords with special shell characters ($ especially.)
The `--password-stdin` flag was introduced in Docker version 17.07.0 so it's been around for a decent amount of time by now. The oldest supported version that doesn't have this flag (enterprise 17.06) is EOL on 2020-04-16, so perhaps this change could be merged in after that date.
This change will solve these open issues:
https://issues.jenkins-ci.org/browse/JENKINS-52761
https://issues.jenkins-ci.org/browse/JENKINS-53770
> docker login - get password from stdin

- .github/workflows/release-drafter.yml
🤖 Beep boop!
This is an automatic pull request that sets up release drafter as GitHub action for your repository.
Currently, you're using the app version of release drafter, which is deprecated since 2019.
Switching to the action is a drop in replacement and requires no further work from your side.
Once you merge this PR, the action is setup. If you want to configure it further, read [here](https://github.com/jenkinsci/.github/blob/master/.github/release-drafter.adoc).
In case of questions, please ping `@NotMyFault`.
Additional information:
- [Click here to read more about the deprecated app](https://github.com/release-drafter/release-drafter/issues/335)
- [Click here to read more about release drafter as GitHub action in Jenkins](https://github.com/jenkinsci/.github/blob/master/.github/re …
> Deprecate Release Drafter app in favor of GitHub workflow

- src/main/java/org/jenkinsci/plugins/docker/commons/tools/DockerTool.java
Update javadoc comment to use `agent` rather than `slave`.
- ~~Ensure you have provided tests - that demonstrates feature works or fixes the issue~~
> Use "agent" in the javadoc rather than "slave"

- src/main/java/org/jenkinsci/plugins/docker/commons/impl/RegistryKeyMaterialFactory.java
- src/test/java/org/jenkinsci/plugins/docker/commons/impl/HostOnlyRegistryKeyMaterialFactoryTest.java
This is a fix for docker workflow plugin issue that manifests when using `podman`. The fix here allows to either directly (based on tool name) or via environment variable to use just how and port of the registry url instead of complete one.
https://issues.jenkins.io/browse/JENKINS-67418
> Allow to use registry as host and port only to allow to use podman as executable

- pom.xml
- src/main/java/org/jenkinsci/plugins/docker/commons/credentials/DockerRegistryToken.java
- src/main/java/org/jenkinsci/plugins/docker/commons/credentials/DockerServerCredentialsHandler.java
- src/main/resources/org/jenkinsci/plugins/docker/commons/credentials/DockerServerCredentials/credentials.jelly
- src/test/java/org/jenkinsci/plugins/docker/commons/tools/DockerToolInstallerTest.java
* subsumes #91 
* parent pom
* Update jenkins core version to `2.263.1`
* use stock `<f:secretTextarea/>`
* Update versions used for smoke tests as older versions have been
removed.
> Update infrastructure for PCT compatibility with recent Jenkins core

- src/main/java/org/jenkinsci/plugins/docker/commons/tools/DockerToolInstaller.java
- src/test/java/org/jenkinsci/plugins/docker/commons/tools/DockerToolInstallerTest.java
Edge channel has 19.03.9 as latest version available
https://download.docker.com/linux/static/edge/x86_64/
Imho it has to be changed  to stable channel
https://download.docker.com/linux/static/stable/x86_64/
> Install docker from stable channel

- src/main/java/org/jenkinsci/plugins/docker/commons/credentials/DockerRegistryEndpoint.java
- src/test/java/org/jenkinsci/plugins/docker/commons/credentials/DockerRegistryEndpointTest.java
[JENKINS-63243](https://issues.jenkins-ci.org/browse/JENKINS-63243)
> [JENKINS-63243] DockerRegistryEndpoint Pattern should accept registry v2 references

- src/test/java/org/jenkinsci/plugins/docker/commons/credentials/DockerServerCredentialsTest.java
Jenkins 2.412 and earlier use a text area for the client key data entry on the credentials page.
Jenkins 2.413 and newer use an input field for the client key data entry on the credentials page.
Jenkins 2.413 looks much nicer with a button that is consistent with the other buttons used in the Jenkins pages.
https://github.com/jenkinsci/jenkins/pull/8179 is the Jenkins core pull request that implemented the change in Jenkins 2.413.  Other plugins that use HTMLUnit to enter a value for the secret text may need a similar change.  Special thanks to @mawinter69 for implementing that improvement in Jenkins 2.413.
Compared the HTML pages generated by 2.412 and 2.413 and confirmed that 2.412 uses a textarea and 2.413 uses an input field.  The 2.413 layout looks much nicer.
Automated test passes …
> Adapt DockerServerCredentialsTest for 2.413+ credentials page

- src/main/java/org/jenkinsci/plugins/docker/commons/impl/RegistryKeyMaterialFactory.java
> Missing newlines in messages from `RegistryKeyMaterialFactory`

- src/main/java/org/jenkinsci/plugins/docker/commons/credentials/KeyMaterial2.java
- src/main/java/org/jenkinsci/plugins/docker/commons/credentials/KeyMaterialContext.java
- src/main/java/org/jenkinsci/plugins/docker/commons/credentials/KeyMaterialFactory.java
- src/main/java/org/jenkinsci/plugins/docker/commons/impl/CompositeKeyMaterialFactory.java
- src/main/java/org/jenkinsci/plugins/docker/commons/impl/NullKeyMaterialFactory.java
- src/main/java/org/jenkinsci/plugins/docker/commons/impl/RegistryKeyMaterialFactory.java
- src/main/java/org/jenkinsci/plugins/docker/commons/impl/ServerHostKeyMaterialFactory.java
- src/main/java/org/jenkinsci/plugins/docker/commons/impl/ServerKeyMaterialFactory.java
- src/main/java/org/jenkinsci/plugins/docker/commons/impl/ServerKeyMaterialFactoryFromDockerCredentials.java
- src/test/java/org/jenkinsci/plugins/docker/commons/credentials/DockerServerEndpointTest.java
- src/test/java/org/jenkinsci/plugins/docker/commons/impl/HostOnlyRegistryKeyMaterialFactoryTest.java
- src/test/java/org/jenkinsci/plugins/docker/commons/impl/RegistryKeyMaterialFactoryTest.java
- src/test/java/org/jenkinsci/plugins/docker/commons/util/SampleDockerBuilder.java
Needed for https://github.com/jenkinsci/docker-workflow-plugin/pull/351.
> [JENKINS-75679] `KeyMaterial` variant passing `VirtualChannel` to `close`
