- src/main/java/org/jenkinsci/plugins/docker/commons/fingerprint/DockerFingerprints.java
- src/main/java/org/jenkinsci/plugins/docker/commons/fingerprint/DockerFromFingerprintFacet.java
- src/main/java/org/jenkinsci/plugins/docker/commons/fingerprint/DockerRunFingerprintFacet.java
- src/main/java/org/jenkinsci/plugins/docker/commons/fingerprint/DockerRunPtrFingerprintFacet.java
Making this closer to usable.
@reviewbybees
> DockerFingerprints tweaks

- src/main/java/org/jenkinsci/plugins/docker/commons/DockerServerEndpoint.java
> Need to mkdir ~/.docker/ if it does not yet exist

- src/main/java/org/jenkinsci/plugins/docker/commons/fingerprint/ContainerRecord.java
> Make ContainerRecord Serializable

- src/main/java/org/jenkinsci/plugins/docker/commons/DockerRegistryEndpoint.java
- src/main/resources/org/jenkinsci/plugins/docker/commons/DockerRegistryEndpoint/help-url.html
Otherwise it asks to login when pushing
@reviewbybees
> Use https for Docker registry

- src/main/java/org/jenkinsci/plugins/docker/commons/DockerServerEndpoint.java
- src/main/java/org/jenkinsci/plugins/docker/commons/KeyMaterial.java
- src/main/java/org/jenkinsci/plugins/docker/commons/KeyMaterialContext.java
- src/main/java/org/jenkinsci/plugins/docker/commons/KeyMaterialFactory.java
- src/main/java/org/jenkinsci/plugins/docker/commons/impl/CompositeKeyMaterialFactory.java
- src/main/java/org/jenkinsci/plugins/docker/commons/impl/ServerHostKeyMaterialFactory.java
- src/main/java/org/jenkinsci/plugins/docker/commons/impl/ServerKeyMaterialFactory.java
> Make composition easier

- src/test/java/org/jenkinsci/plugins/docker/commons/ConfigTest.java
Should have been part of #15 but was forgotten I guess. @reviewbybees
> DockerServerCredentials is now concrete, so we can test its use

- src/main/java/org/jenkinsci/plugins/docker/commons/fingerprint/ContainerRecord.java
- src/main/java/org/jenkinsci/plugins/docker/commons/fingerprint/DockerFingerprints.java
- src/test/java/org/jenkinsci/plugins/docker/commons/fingerprint/DockerRunFingerprintFacetTest.java
Removing some duplication.
@reviewbybees
> Cleaning up DockerFingerprints.addRunFacet method sig

- src/main/java/org/jenkinsci/plugins/docker/commons/fingerprint/DockerFingerprintAction.java
- src/main/java/org/jenkinsci/plugins/docker/commons/fingerprint/DockerFingerprints.java
- src/main/resources/org/jenkinsci/plugins/docker/commons/Messages.properties
- src/main/resources/org/jenkinsci/plugins/docker/commons/fingerprint/DockerFingerprintAction/index.jelly
- src/main/resources/org/jenkinsci/plugins/docker/commons/fingerprint/DockerFingerprintAction/index.properties
- src/test/java/org/jenkinsci/plugins/docker/commons/fingerprint/DockerRunFingerprintFacetTest.java
This action allows to...
* Navigate to Docker fingerprints from Runs
* Quickly search fingerprints by Run
Plan:
@reviewbybees
> Docker Fingerprint Actions

- src/main/java/org/jenkinsci/plugins/docker/commons/DockerServerEndpoint.java
- src/test/java/org/jenkinsci/plugins/docker/commons/DockerServerEndpointTest.java
> Stray subdirectories of ~/.docker/

- src/main/java/org/jenkinsci/plugins/docker/commons/DockerTool.java
- src/test/java/org/jenkinsci/plugins/docker/commons/DockerToolTest.java
- src/test/java/org/jenkinsci/plugins/docker/commons/SampleDockerBuilder.java
> Fixing DockerTool API to support ToolInstaller

- src/main/java/org/jenkinsci/plugins/docker/commons/fingerprint/DockerFingerprintAction.java
- src/main/java/org/jenkinsci/plugins/docker/commons/fingerprint/DockerFingerprintFacet.java
- src/main/java/org/jenkinsci/plugins/docker/commons/fingerprint/DockerRunPtrFingerprintFacet.java
- src/main/resources/org/jenkinsci/plugins/docker/commons/fingerprint/DockerFingerprintAction/index.jelly
Introduces DockerFingerprintFacet base class, which may contribute the UI. The current implementation allows to add summaries to DockerFingerprintAction. It allows to make it much more informative.
@reviewbybees
> Docker Facets Base class + summaries in the UI

- src/main/java/org/jenkinsci/plugins/docker/commons/fingerprint/DockerFingerprintAction.java
- src/main/java/org/jenkinsci/plugins/docker/commons/fingerprint/DockerFingerprints.java
> DockerFingerprints API update

- src/main/java/org/jenkinsci/plugins/docker/commons/credentials/DockerRegistryToken.java
Docker 1.7 introduced `.docker/config.json` which offer configuration extensibility. This file is preferred over `.dockercfg`, so if docker node has already ran some docker stuff with 1.7, jenkins just can't set credentials based on `.dockercfg`
> Support Docker 1.7+ .docker/config.json

- src/main/java/org/jenkinsci/plugins/docker/commons/tools/DockerTool.java
- src/main/java/org/jenkinsci/plugins/docker/commons/tools/DockerToolInstaller.java
- src/main/resources/org/jenkinsci/plugins/docker/commons/tools/DockerToolInstaller/config.jelly
Download docker executable from docker.io and install automatically on slave
Please note: this do install docker cli for client operation, can't be used to run daemon which require extra setup.
> Docker Tool Installer

- pom.xml
So Jenkins can pick up the results
@reviewbybees
> Configure findbugs xml output

- pom.xml
- src/main/java/org/jenkinsci/plugins/docker/commons/credentials/DockerRegistryEndpoint.java
- src/main/java/org/jenkinsci/plugins/docker/commons/credentials/DockerRegistryToken.java
- src/main/java/org/jenkinsci/plugins/docker/commons/credentials/DockerServerEndpoint.java
- src/main/java/org/jenkinsci/plugins/docker/commons/fingerprint/ContainerRecord.java
- src/main/java/org/jenkinsci/plugins/docker/commons/fingerprint/DockerRunPtrFingerprintFacet.java
- src/main/java/org/jenkinsci/plugins/docker/commons/impl/ServerKeyMaterialFactory.java
- src/main/java/org/jenkinsci/plugins/docker/commons/tools/DockerToolInstaller.java
> Fix findbugs issues

- src/main/java/org/jenkinsci/plugins/docker/commons/fingerprint/DockerFingerprints.java
The fix also changes the default behavior for missing names. Instead of non-informative "<docker-image>" we will be using "Docker image $(64-char id)" (which may be too long BTW)
@reviewbybees
> [FIXED JENKINS-28657] - Support the creation of named fingerprints

- src/main/java/org/jenkinsci/plugins/docker/commons/fingerprint/DockerFingerprintAction.java
@oleg-nenashev rtfm ;-)
https://github.com/jenkinsci/icon-shim-plugin/blob/master/icon-set/src/main/java/org/jenkins/ui/icon/IconSpec.java#L39
Verified manually with `hpi:run`
> [JENKINS-28776] Fix broken icon.

- pom.xml
- src/main/java/org/jenkinsci/plugins/docker/commons/credentials/DockerRegistryToken.java
- src/main/java/org/jenkinsci/plugins/docker/commons/fingerprint/DockerFingerprintFacet.java
- src/main/java/org/jenkinsci/plugins/docker/commons/fingerprint/DockerFingerprints.java
- src/main/java/org/jenkinsci/plugins/docker/commons/tools/DockerToolInstaller.java
See [JENKINS-35018](https://issues.jenkins-ci.org/browse/JENKINS-35018)
@reviewbybees
> [JENKINS-35018] Migrate to new parent POM

- src/test/java/org/jenkinsci/plugins/docker/commons/fingerprint/DockerFingerprintsTest.java
[JENKINS-32792](https://issues.jenkins-ci.org/browse/JENKINS-32792)
@reviewbybees
> [JENKINS-32792] Add test for sha256 fingerprints

- pom.xml
- src/main/java/org/jenkinsci/plugins/docker/commons/tools/DockerToolInstaller.java
- src/main/resources/org/jenkinsci/plugins/docker/commons/tools/Messages.properties
- src/test/java/org/jenkinsci/plugins/docker/commons/tools/DockerToolInstallerTest.java
[JENKINS-32790](https://issues.jenkins-ci.org/browse/JENKINS-32790) & [JENKINS-36082](https://issues.jenkins-ci.org/browse/JENKINS-36082) and finally providing a test for it.
@reviewbybees
> [JENKINS-36082] [JENKINS-32790] DockerToolInstaller was broken

- src/main/java/org/jenkinsci/plugins/docker/commons/tools/DockerToolInstaller.java
- src/main/resources/org/jenkinsci/plugins/docker/commons/tools/DockerToolInstaller/help-version.html
- src/test/java/org/jenkinsci/plugins/docker/commons/tools/DockerToolInstallerTest.java
Amends #63 by @denisa.
@reviewbybees
> [JENKINS-48674] Fix installer

- pom.xml
- src/main/java/org/jenkinsci/plugins/docker/commons/fingerprint/DockerFingerprints.java
@reviewbybees 
@jglick, bumping the required core version just to satisfy the PCT doesn't sit well with me, but filing the PR anyway for you to accept or reject.
https://issues.jenkins-ci.org/browse/JENKINS-49075
> [JENKINS-49075] Bump parent pom and a few other dependencies

- src/main/java/org/jenkinsci/plugins/docker/commons/credentials/DockerRegistryEndpoint.java
- src/main/java/org/jenkinsci/plugins/docker/commons/credentials/DockerRegistryToken.java
- src/main/java/org/jenkinsci/plugins/docker/commons/impl/RegistryKeyMaterialFactory.java
- src/test/java/org/jenkinsci/plugins/docker/commons/util/SampleDockerBuilder.java
[JENKINS-51397](https://issues.jenkins-ci.org/browse/JENKINS-51397)
> [JENKINS-51397] Define API for passing environment to docker login command

- src/main/java/org/jenkinsci/plugins/docker/commons/DockerImageExtractor.java
- src/main/java/org/jenkinsci/plugins/docker/commons/credentials/DockerRegistryEndpoint.java
- src/main/java/org/jenkinsci/plugins/docker/commons/credentials/DockerServerEndpoint.java
- src/main/java/org/jenkinsci/plugins/docker/commons/fingerprint/DockerFingerprints.java
- src/main/java/org/jenkinsci/plugins/docker/commons/impl/UsernamePasswordDockerRegistryTokenSource.java
- src/main/java/org/jenkinsci/plugins/docker/commons/tools/DockerTool.java
- src/test/java/org/jenkinsci/plugins/docker/commons/credentials/DockerRegistryEndpointTest.java
- src/test/java/org/jenkinsci/plugins/docker/commons/credentials/DockerServerCredentialsBindingTest.java
- src/test/java/org/jenkinsci/plugins/docker/commons/credentials/DockerServerCredentialsHandlerTest.java
- src/test/java/org/jenkinsci/plugins/docker/commons/credentials/DockerServerCredentialsTest.java
- src/test/java/org/jenkinsci/plugins/docker/commons/credentials/DockerServerDomainSpecificationTest.java
- src/test/java/org/jenkinsci/plugins/docker/commons/credentials/DockerServerEndpointTest.java
- src/test/java/org/jenkinsci/plugins/docker/commons/impl/RegistryKeyMaterialFactoryTest.java
- src/test/java/org/jenkinsci/plugins/docker/commons/tools/DockerToolInstallerTest.java
Replaces some deprecated APIs.
---------------------------------
> Replace deprecated calls

- src/main/java/org/jenkinsci/plugins/docker/commons/DockerImageExtractor.java
- src/main/java/org/jenkinsci/plugins/docker/commons/credentials/DockerRegistryEndpoint.java
- src/main/java/org/jenkinsci/plugins/docker/commons/credentials/DockerRegistryToken.java
- src/main/java/org/jenkinsci/plugins/docker/commons/credentials/DockerServerCredentials.java
- src/main/java/org/jenkinsci/plugins/docker/commons/credentials/DockerServerCredentialsBinding.java
- src/main/java/org/jenkinsci/plugins/docker/commons/credentials/DockerServerCredentialsHandler.java
- src/main/java/org/jenkinsci/plugins/docker/commons/credentials/DockerServerDomainSpecification.java
- src/main/java/org/jenkinsci/plugins/docker/commons/credentials/DockerServerEndpoint.java
- src/main/java/org/jenkinsci/plugins/docker/commons/credentials/ImageNameValidator.java
- src/main/java/org/jenkinsci/plugins/docker/commons/credentials/KeyMaterialContext.java
- src/main/java/org/jenkinsci/plugins/docker/commons/credentials/KeyMaterialFactory.java
- src/main/java/org/jenkinsci/plugins/docker/commons/impl/NullKeyMaterialFactory.java
- src/main/java/org/jenkinsci/plugins/docker/commons/impl/RegistryKeyMaterialFactory.java
- src/main/java/org/jenkinsci/plugins/docker/commons/impl/ServerHostKeyMaterialFactory.java
- src/main/java/org/jenkinsci/plugins/docker/commons/impl/ServerKeyMaterialFactory.java
- src/main/java/org/jenkinsci/plugins/docker/commons/impl/UsernamePasswordDockerRegistryTokenSource.java
- src/main/java/org/jenkinsci/plugins/docker/commons/tools/DockerTool.java
- src/main/java/org/jenkinsci/plugins/docker/commons/tools/DockerToolInstaller.java
- src/test/java/org/jenkinsci/plugins/docker/commons/credentials/DockerServerCredentialsHandlerTest.java
- src/test/java/org/jenkinsci/plugins/docker/commons/credentials/DockerServerCredentialsTest.java
- src/test/java/org/jenkinsci/plugins/docker/commons/util/SampleDockerBuilder.java
Removes JSR 305 and adds missing annotations.
-----------------
> Remove JSR 305

- src/main/resources/org/jenkinsci/plugins/docker/commons/fingerprint/DockerFingerprintAction/index.jelly
Corrects https://github.com/jenkinsci/docker-commons-plugin/pull/61
cc @jglick @oleg-nenashev
> Remove icon-shim

- src/main/java/org/jenkinsci/plugins/docker/commons/impl/RegistryKeyMaterialFactory.java
This reverts commit f3e1aa3e579952fd2e2823e4cf22de209a6d0fc0.
> [JENKINS-69432, JENKINS-69436] Revert #86 "docker login - get password from stdin"

- .github/CODEOWNERS
- .mvn/extensions.xml
- Jenkinsfile
- pom.xml
Supersedes #115, #117, #118, #121, #125.
> Plugin metadata refresh to 2.361.x

- src/main/java/org/jenkinsci/plugins/docker/commons/DockerImageExtractor.java
- src/main/java/org/jenkinsci/plugins/docker/commons/fingerprint/ContainerRecord.java
- src/main/java/org/jenkinsci/plugins/docker/commons/fingerprint/DockerAncestorFingerprintFacet.java
- src/main/java/org/jenkinsci/plugins/docker/commons/fingerprint/DockerDescendantFingerprintFacet.java
- src/main/java/org/jenkinsci/plugins/docker/commons/fingerprint/DockerFingerprintAction.java
- src/main/java/org/jenkinsci/plugins/docker/commons/fingerprint/DockerFingerprints.java
- src/main/java/org/jenkinsci/plugins/docker/commons/impl/CompositeKeyMaterialFactory.java
- src/main/java/org/jenkinsci/plugins/docker/commons/tools/DockerTool.java
- src/main/java/org/jenkinsci/plugins/docker/commons/tools/DockerToolInstaller.java
Several years ago, Jenkins core switched from the abandoned JSR 305 annotations to SpotBugs annotations, but this plugin never caught up. This PR adapts this plugin to the common convention used in Jenkins core and the vast majority of other Jenkins plugins.
> EOL JSR 305
